/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import clases.conectar;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class estracto extends javax.swing.JFrame {

    /**
     * Creates new form estracto
     */
    conectar con=new conectar();
        Connection reg=con.conectar();
    public estracto() {
        initComponents();
        
        this.setTitle("Cajero BMS");
        this.setLocationRelativeTo(estracto.this);
        this.setResizable(false);
        this.setVisible(true);
        Date fecha = new Date();
        DateFormat formato = DateFormat.getDateInstance(DateFormat.FULL);
        
        fechaaa.setText(formato.format(fecha));
        
        
        //String campo="5500";
       //String where= "";
       //if(!"".equals(campo)){
           //where ="where pass = '" + campo + "'";
       //}
       
    try {
        DefaultTableModel modelo=new DefaultTableModel();
        deposito.setModel(modelo);
        Statement st= reg.createStatement();
        ResultSet rs=st.executeQuery("select * from deposito "/*+where*/);
        ResultSetMetaData rsMd = rs.getMetaData();
        int cantidadcolumnas=rsMd.getColumnCount();
        modelo.addColumn("Descripcion");
        modelo.addColumn("Monto");
        modelo.addColumn("Fecha");
        int anchos[]={100,100,100};
        for(int x=0; x<cantidadcolumnas; x++){
            deposito.getColumnModel().getColumn(x).setPreferredWidth(anchos[x]);
        }
        while(rs.next()){
           Object filas[]=new Object[cantidadcolumnas];
           for(int i=0; i<cantidadcolumnas; i++){
               filas[i]=rs.getObject(i+1);
           }
           modelo.addRow(filas);
        }        
    } catch (SQLException ex) {
  }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        volver = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bolivianos = new javax.swing.JButton();
        fechaaa = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        deposito = new javax.swing.JTable();
        retiro1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(17, 66, 50));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 65, 75));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        volver.setBackground(new java.awt.Color(204, 204, 204));
        volver.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        volver.setForeground(new java.awt.Color(17, 66, 50));
        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-izquierda-en-círculo-2-32.png"))); // NOI18N
        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        jPanel2.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 120, 40));

        jLabel6.setFont(new java.awt.Font("Bodoni MT Poster Compressed", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Bolivia");
        jLabel6.setAlignmentX(2.0F);
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 110, 30));

        jLabel7.setFont(new java.awt.Font("Bodoni MT Poster Compressed", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("BANCO LA FLORIDA");
        jLabel7.setAlignmentX(2.0F);
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 280, 40));

        bolivianos.setBackground(new java.awt.Color(204, 204, 204));
        bolivianos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bolivianos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-imprimir-32.png"))); // NOI18N
        bolivianos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bolivianosActionPerformed(evt);
            }
        });
        jPanel2.add(bolivianos, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 640, 100, 40));

        fechaaa.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        fechaaa.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(fechaaa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, 40));

        deposito.setBackground(new java.awt.Color(0, 65, 75));
        deposito.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 65, 75)));
        deposito.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        deposito.setForeground(new java.awt.Color(204, 204, 204));
        deposito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Descripcion", "Monto", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        deposito.setToolTipText("");
        deposito.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        deposito.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        deposito.setFillsViewportHeight(true);
        deposito.setGridColor(new java.awt.Color(0, 102, 102));
        deposito.setInheritsPopupMenu(true);
        deposito.setMinimumSize(new java.awt.Dimension(100, 40));
        deposito.setPreferredSize(new java.awt.Dimension(800, 40));
        deposito.setRowHeight(40);
        deposito.setSelectionBackground(new java.awt.Color(255, 255, 255));
        deposito.setSelectionForeground(new java.awt.Color(0, 0, 0));
        deposito.setShowHorizontalLines(false);
        deposito.setShowVerticalLines(false);
        deposito.setUpdateSelectionOnSort(false);
        deposito.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(deposito);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 490, 440));

        retiro1.setBackground(new java.awt.Color(204, 204, 204));
        retiro1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        retiro1.setForeground(new java.awt.Color(17, 66, 50));
        retiro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-eliminar-32.png"))); // NOI18N
        retiro1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retiro1ActionPerformed(evt);
            }
        });
        jPanel2.add(retiro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 640, 100, 40));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("MOVIMIENTOS");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 710, 240, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 830, 790));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        new menu();
        this.dispose();
    }//GEN-LAST:event_volverActionPerformed

    private void bolivianosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bolivianosActionPerformed
        JOptionPane.showMessageDialog(null, "Imprimiendo");
        new menu();
        this.dispose();
        
        /*
        String campo="Luis";
        String where= "";
        if(!"".equals(campo)){
            where ="where nombre = '" + campo + "'";
        }

        conectar con=new conectar();
        Connection reg=con.conectar();
        try {
            DefaultTableModel modelo=new DefaultTableModel();
            jtpersonas.setModel(modelo);
            Statement st= reg.createStatement();
            ResultSet rs=st.executeQuery("select nombre, apellido, saldo from usuario "+where);
            ResultSetMetaData rsMd = rs.getMetaData();
            int cantidadcolumnas=rsMd.getColumnCount();
            modelo.addColumn("Nombre");
            modelo.addColumn("Apellido");
            modelo.addColumn("Saldo");
            int anchos[]={20,20,100};
            for(int x=0; x<cantidadcolumnas; x++){
                jtpersonas.getColumnModel().getColumn(x).setPreferredWidth(anchos[x]);
            }
            while(rs.next()){
                Object filas[]=new Object[cantidadcolumnas];
                for(int i=0; i<cantidadcolumnas; i++){
                    filas[i]=rs.getObject(i+1);
                }
                modelo.addRow(filas);
            }
        } catch (SQLException ex) {
            Logger.getLogger(ingresar.class.getName()).log(Level.SEVERE, null, ex);
        } */

    }//GEN-LAST:event_bolivianosActionPerformed

    private void retiro1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retiro1ActionPerformed
        
        try {
           String fecha=JOptionPane.showInputDialog("Ingresa una fecha");
            String sql="DELETE FROM deposito WHERE fecha='"+fecha+"'";
            PreparedStatement ps;
            ps = reg.prepareStatement(sql);
           int rs=ps.executeUpdate();
           if(rs>0){
               JOptionPane.showMessageDialog(null, "Registro Eliminado");
               new estracto();
               this.dispose();
           }  
           else{
                JOptionPane.showMessageDialog(null, "Error al Eliminar");
           }
           
        } catch (SQLException ex) {
            
        }
    }//GEN-LAST:event_retiro1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(estracto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(estracto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(estracto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(estracto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new estracto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bolivianos;
    private javax.swing.JTable deposito;
    private javax.swing.JLabel fechaaa;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton retiro1;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
