/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import clases.conectar;
import static interfaces.saldo.nn;
import static interfaces.saldo.pasas;
import static interfaces.saldo.saldos;
import static interfaces.saldo.ss;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.UIManager;

/**
 *
 * @author USUARIO
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form index
     */
    private static int cont = 3 ;
    public login() {
        initComponents();
        aa.setBackground(new Color(0, 65, 75));
         //c.setBackground(new Color(0,0,0,64));
         //cc.setBackground(new Color(0,0,0,64));
         /*ImageIcon fot = new ImageIcon("src/imagenes/ddd.jpg");
        Icon icono = new ImageIcon(fot.getImage().getScaledInstance(dd.getWidth(), dd.getHeight(), Image.SCALE_DEFAULT));
        dd.setIcon(icono);
        this.repaint();*/
        
        this.setTitle("Cajero BMS");
        this.setLocationRelativeTo(login.this);
        this.setResizable(false);
        this.setVisible(true);
        Date fecha = new Date();
        DateFormat formato = DateFormat.getDateInstance(DateFormat.FULL);
        
        fechaaa.setText(formato.format(fecha));
        
    }
   
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        entrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        fechaaa = new javax.swing.JLabel();
        c = new javax.swing.JTextField();
        salir = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        contra = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        aa = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(17, 66, 50));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 65, 75));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        entrar.setBackground(new java.awt.Color(204, 204, 204));
        entrar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        entrar.setForeground(new java.awt.Color(17, 66, 50));
        entrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-introducir-pin-32.png"))); // NOI18N
        entrar.setText("Listo");
        entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarActionPerformed(evt);
            }
        });
        jPanel2.add(entrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 660, 110, 40));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contraseña :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 150, 50));

        fechaaa.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        fechaaa.setForeground(new java.awt.Color(255, 255, 255));
        fechaaa.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                fechaaaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel2.add(fechaaa, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 740, 340, 30));

        c.setEditable(false);
        c.setBackground(new java.awt.Color(0, 65, 75));
        c.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        c.setForeground(new java.awt.Color(204, 204, 204));
        c.setBorder(null);
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });
        jPanel2.add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 400, 40));

        salir.setBackground(new java.awt.Color(204, 204, 204));
        salir.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        salir.setForeground(new java.awt.Color(17, 66, 50));
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-cancelar-32.png"))); // NOI18N
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jPanel2.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 100, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user(1).jpg"))); // NOI18N
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 210, 190));

        jLabel6.setFont(new java.awt.Font("Bodoni MT Poster Compressed", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Bolivia");
        jLabel6.setAlignmentX(2.0F);
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 110, 30));

        jLabel7.setFont(new java.awt.Font("Bodoni MT Poster Compressed", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("BANCO LA FLORIDA");
        jLabel7.setAlignmentX(2.0F);
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 280, 40));

        contra.setBackground(new java.awt.Color(0, 65, 75));
        contra.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        contra.setForeground(new java.awt.Color(204, 204, 204));
        contra.setBorder(null);
        contra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraActionPerformed(evt);
            }
        });
        jPanel2.add(contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 530, 400, 40));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 570, 400, 10));

        aa.setBackground(new java.awt.Color(102, 102, 255));
        aa.setForeground(new java.awt.Color(0, 255, 0));
        jPanel2.add(aa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 790));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 460, 790));

        jPanel3.setBackground(new java.awt.Color(17, 66, 50));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/colgantevertical-bristolmedicine-web1024-9103a3c340d9dae74215119300297473-1024-1024 (2).jpg"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 790));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 360, 790));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 811, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void limpiar(){
   contra.setText("");
}
    public static void esperar(int segundos){
        try {
            Thread.sleep(segundos * 1000);
         } catch (Exception e) {
            System.out.println(e);
         }
    }  
    
    private void entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarActionPerformed
       
        conectar con=new conectar();
        Connection reg=con.conectar();
   try {
       
        Statement ps= reg.createStatement();
     ResultSet rs=ps.executeQuery("select * from usuario ");
         while(rs.next()){
                nn=rs.getString("nombre");
                ss=rs.getString("pass"); 
        }
                    
            String pass=contra.getText();
            if(!pass.equals("")){
             if(pass.equals(ss)){
                    //JOptionPane.showMessageDialog(null,"Bienvenido : "+nn+" gracias por su preferencia.");
                    //new menu();
                    //this.dispose();
                    cont = -1;
                    limpiar();
                    c.setText("Bienvenido "+nn);
             } else {
                 cont --;
                JOptionPane.showMessageDialog(null,"Contraseña incorrecta te quedan: "+cont+" intentos.");
                limpiar();
             }
             if(cont==0){
                 JOptionPane.showMessageDialog(null,"Se ha detectado intentos erroreos en su cuenta, ser realizara un bloqueo temporal a su cuenta.");
                 }  
            }
            else{
                JOptionPane.showMessageDialog(null,"Campo vacio, ingrese su contraseña.");
            }
  
   } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
       }
   if(cont==0){
                new main();
                this.dispose();
       }
   if(cont ==-1){
   Timer timer = new Timer (5000, new ActionListener ()
{
    public void actionPerformed(ActionEvent e)
    {
        if(cont==-1){
            new menu();
            dispose();
            cont=-2;
       } 
    }
    });
    timer.start();}
    }//GEN-LAST:event_entrarActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        JOptionPane.showMessageDialog(null, "Gracias por su prefencia.");
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cActionPerformed

    private void fechaaaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_fechaaaAncestorAdded
        
    }//GEN-LAST:event_fechaaaAncestorAdded

    private void contraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        //</editor-fold>
        //</editor-fold>
/*try {
            //Plastic3DLookAndFeel.setPlasticTheme(new DarkStar());
            UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aa;
    private javax.swing.JTextField c;
    public javax.swing.JPasswordField contra;
    private javax.swing.JButton entrar;
    private javax.swing.JLabel fechaaa;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables

        
}
