/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.Color;
import java.awt.Image;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author USUARIO
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form pagina1
     */
    public menu() {
        initComponents();
        
        aa.setBackground(new Color(0, 65, 75));
        
        ImageIcon fot = new ImageIcon("src/imagenes/coca.gif");
        Icon icono = new ImageIcon(fot.getImage().getScaledInstance(banner1.getWidth(), banner1.getHeight(), Image.SCALE_DEFAULT));
        banner1.setIcon(icono);
        this.repaint();
        
        ImageIcon foto = new ImageIcon("src/imagenes/tt.gif");
        Icon iconos = new ImageIcon(foto.getImage().getScaledInstance(banner3.getWidth(), banner3.getHeight(), Image.SCALE_DEFAULT));
        banner3.setIcon(iconos);
        this.repaint();

        
        this.setTitle("Cajero BMS");
        this.setLocationRelativeTo(menu.this);
        this.setResizable(false);
        this.setVisible(true);
        
        Date fecha = new Date();
        DateFormat formato = DateFormat.getDateInstance(DateFormat.FULL);
        
        fechaaa.setText(formato.format(fecha));
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        extracto = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        volver = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        deposito = new javax.swing.JButton();
        retiro = new javax.swing.JButton();
        saldo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        fechaaa = new javax.swing.JLabel();
        salir = new javax.swing.JButton();
        aa = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        banner3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        banner1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(17, 66, 50));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 65, 75));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        extracto.setBackground(new java.awt.Color(204, 204, 204));
        extracto.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        extracto.setForeground(new java.awt.Color(17, 66, 50));
        extracto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-lista-de-ingredientes-32.png"))); // NOI18N
        extracto.setText("Extracto");
        extracto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extractoActionPerformed(evt);
            }
        });
        jPanel2.add(extracto, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, 130, 40));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("MENU DE SERVICIOS");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 240, 30));

        volver.setBackground(new java.awt.Color(204, 204, 204));
        volver.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        volver.setForeground(new java.awt.Color(17, 66, 50));
        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-izquierda-en-círculo-2-32.png"))); // NOI18N
        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        jPanel2.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 120, 40));

        jLabel6.setFont(new java.awt.Font("Bodoni MT Poster Compressed", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Bolivia");
        jLabel6.setAlignmentX(2.0F);
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 110, 30));

        jLabel7.setFont(new java.awt.Font("Bodoni MT Poster Compressed", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("BANCO LA FLORIDA");
        jLabel7.setAlignmentX(2.0F);
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 280, 40));

        deposito.setBackground(new java.awt.Color(204, 204, 204));
        deposito.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        deposito.setForeground(new java.awt.Color(17, 66, 50));
        deposito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-efectivo-en-mano-32.png"))); // NOI18N
        deposito.setText("Deposito");
        deposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositoActionPerformed(evt);
            }
        });
        jPanel2.add(deposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 140, 40));

        retiro.setBackground(new java.awt.Color(204, 204, 204));
        retiro.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        retiro.setForeground(new java.awt.Color(17, 66, 50));
        retiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-efectivo-en-mano-32(1).png"))); // NOI18N
        retiro.setText("Retiro");
        retiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retiroActionPerformed(evt);
            }
        });
        jPanel2.add(retiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 130, 40));

        saldo.setBackground(new java.awt.Color(204, 204, 204));
        saldo.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        saldo.setForeground(new java.awt.Color(17, 66, 50));
        saldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-bolsa-de-dinero-32.png"))); // NOI18N
        saldo.setText("Saldo");
        saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoActionPerformed(evt);
            }
        });
        jPanel2.add(saldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 140, 40));

        jLabel2.setBackground(new java.awt.Color(204, 0, 102));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-retirada-256.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 260, 260));

        fechaaa.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        fechaaa.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(fechaaa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 30));

        salir.setBackground(new java.awt.Color(204, 204, 204));
        salir.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        salir.setForeground(new java.awt.Color(17, 66, 50));
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-cancelar-32.png"))); // NOI18N
        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        jPanel2.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 460, 100, 40));
        jPanel2.add(aa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 510));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 830, 510));

        jPanel3.setBackground(new java.awt.Color(0, 65, 75));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(banner3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 130));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 670, 830, 130));

        jPanel4.setBackground(new java.awt.Color(0, 65, 75));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        banner1.setBackground(new java.awt.Color(0, 65, 75));
        jPanel4.add(banner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 130));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 830, 130));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void extractoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extractoActionPerformed
        new estracto();
        this.dispose();
    }//GEN-LAST:event_extractoActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        new login();
        this.dispose();
    }//GEN-LAST:event_volverActionPerformed

    private void depositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositoActionPerformed
        new depositar();
        this.dispose();
    }//GEN-LAST:event_depositoActionPerformed

    private void retiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retiroActionPerformed
        new retiro();
        this.dispose();
    }//GEN-LAST:event_retiroActionPerformed

    private void saldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldoActionPerformed
        new saldo();
        this.dispose();
    }//GEN-LAST:event_saldoActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        new login();
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
/*try {
            //Plastic3DLookAndFeel.setPlasticTheme(new DarkStar());
            UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aa;
    public javax.swing.JLabel banner1;
    private javax.swing.JLabel banner3;
    private javax.swing.JButton deposito;
    private javax.swing.JButton extracto;
    private javax.swing.JLabel fechaaa;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton retiro;
    private javax.swing.JButton saldo;
    private javax.swing.JButton salir;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
