/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import clases.conectar;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class promedio extends javax.swing.JFrame {

    /**
     * Creates new form promedio
     */
    private static float proo=0;
    public promedio() {
        initComponents();
        setLocationRelativeTo(null);       
        setSize(853, 810);
        this.setTitle("Cajero BMS");
        this.setLocationRelativeTo(promedio.this);
        this.setResizable(false);
        this.setVisible(true);
        Date fecha = new Date();
        DateFormat formato = DateFormat.getDateInstance(DateFormat.FULL);
        
        fechaaa.setText(formato.format(fecha));
        
   
       
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        volver = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bolivianos = new javax.swing.JButton();
        pro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        fechaaa = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        banner2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(17, 66, 50));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 65, 75));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Promedio");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 170, 40));

        volver.setBackground(new java.awt.Color(204, 204, 204));
        volver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        volver.setForeground(new java.awt.Color(17, 66, 50));
        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-izquierda-en-círculo-2-32.png"))); // NOI18N
        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        jPanel2.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 120, 40));

        jLabel6.setFont(new java.awt.Font("Bodoni MT Poster Compressed", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Bolivia");
        jLabel6.setAlignmentX(2.0F);
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 110, 30));

        jLabel7.setFont(new java.awt.Font("Bodoni MT Poster Compressed", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("BANCO LA FLORIDA");
        jLabel7.setAlignmentX(2.0F);
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 280, 40));

        jLabel2.setBackground(new java.awt.Color(204, 0, 102));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-retirada-256.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 260, 260));

        bolivianos.setBackground(new java.awt.Color(204, 204, 204));
        bolivianos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bolivianos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-efectivo-en-mano-32.png"))); // NOI18N
        bolivianos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bolivianosActionPerformed(evt);
            }
        });
        jPanel2.add(bolivianos, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 580, 100, 40));

        pro.setBackground(new java.awt.Color(0, 65, 75));
        pro.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        pro.setForeground(new java.awt.Color(204, 204, 204));
        pro.setBorder(null);
        jPanel2.add(pro, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 580, 50));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Consultas");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 710, 170, 30));

        fechaaa.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        fechaaa.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(fechaaa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 360, 40));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 490, 580, 10));
        jPanel2.add(banner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 790));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 830, 790));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bolivianosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bolivianosActionPerformed
        conectar con=new conectar();
        Connection reg=con.conectar();
        
        //PARA SACAR PROMEDIO CUANDO SE INTRODUSCA UNA FECHA Y USD O BS
       /* String fecha=pro.getText();
        try {
        Statement ps= reg.createStatement();
     ResultSet rs=ps.executeQuery("SELECT MAX(monto) FROM deposito WHERE des='Deposito en usd.' AND fecha='"+fecha+"'");
         if(rs.next()){
                //nnn=rs.getFloat((1));
                proo=rs.getFloat((1));
                pro.setText("");
                proo=(float) (proo/6.90);
        }
            pro.setText(proo+" Dolares"+" max depositado en fecha: "+fecha); 
            //pro.setText((nnn/6.90) + " max depositado en usd."); 
   } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
       }*/ 
        
        
        //float nnn=0;
       //PARA SACAR PROMEDIO CUANDO SEA USD 
   try {
        Statement ps= reg.createStatement();
     ResultSet rs=ps.executeQuery("SELECT AVG(monto) FROM deposito WHERE des='Deposito en usd.'");
         if(rs.next()){
                //nnn=rs.getFloat((1));
                proo=rs.getFloat((1));
                proo=(float) (proo/6.90);
        }
            pro.setText( proo+" max depositado en usd."); 
            //pro.setText((nnn/6.90) + " max depositado en usd."); 
   } catch (Exception e){
            JOptionPane.showMessageDialog(null, e);
       } 
    }//GEN-LAST:event_bolivianosActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        new login();
        this.dispose();
    }//GEN-LAST:event_volverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(promedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(promedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(promedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(promedio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new promedio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel banner2;
    private javax.swing.JButton bolivianos;
    private javax.swing.JLabel fechaaa;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField pro;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
