/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.text.DateFormat;
import java.util.Date;

/**
 *
 * @author USUARIO
 */
public class retiro extends javax.swing.JFrame {

    /**
     * Creates new form retiro
     */
    public retiro() {
        initComponents();
        setLocationRelativeTo(null);       
        setSize(853, 810); 
        this.setTitle("Cajero BMS");
        this.setLocationRelativeTo(retiro.this);
        this.setResizable(false);
        this.setVisible(true);
        Date fecha = new Date();
        DateFormat formato = DateFormat.getDateInstance(DateFormat.FULL);
        
        fechaaa.setText(formato.format(fecha));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        volver = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bolivianos = new javax.swing.JButton();
        bolivianos1 = new javax.swing.JButton();
        fechaaa = new javax.swing.JLabel();
        banner2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(17, 66, 50));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 65, 75));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("    MENU RETIRO");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 700, 240, 30));

        volver.setBackground(new java.awt.Color(204, 204, 204));
        volver.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-izquierda-en-círculo-2-32.png"))); // NOI18N
        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        jPanel2.add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 120, 40));

        jLabel6.setFont(new java.awt.Font("Bodoni MT Poster Compressed", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 153));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Bolivia");
        jLabel6.setAlignmentX(2.0F);
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 110, 30));

        jLabel7.setFont(new java.awt.Font("Bodoni MT Poster Compressed", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 153));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("BANCO LA FLORIDA");
        jLabel7.setAlignmentX(2.0F);
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 280, 40));

        jLabel2.setBackground(new java.awt.Color(204, 0, 102));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-retirada-256.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 260, 260));

        bolivianos.setBackground(new java.awt.Color(204, 204, 204));
        bolivianos.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        bolivianos.setForeground(new java.awt.Color(17, 66, 50));
        bolivianos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-efectivo-en-mano-32(1).png"))); // NOI18N
        bolivianos.setText("Retiro Dolares");
        bolivianos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bolivianosActionPerformed(evt);
            }
        });
        jPanel2.add(bolivianos, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 410, 210, 70));

        bolivianos1.setBackground(new java.awt.Color(204, 204, 204));
        bolivianos1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        bolivianos1.setForeground(new java.awt.Color(17, 66, 50));
        bolivianos1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-efectivo-en-mano-32(1).png"))); // NOI18N
        bolivianos1.setText("Retiro Bolivianos");
        bolivianos1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bolivianos1ActionPerformed(evt);
            }
        });
        jPanel2.add(bolivianos1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, 220, 70));

        fechaaa.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        fechaaa.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(fechaaa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 400, 50));
        jPanel2.add(banner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 790));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 830, 790));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        new menu();
        this.dispose();
    }//GEN-LAST:event_volverActionPerformed

    private void bolivianosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bolivianosActionPerformed
        new retdolar();
        this.dispose();
    }//GEN-LAST:event_bolivianosActionPerformed

    private void bolivianos1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bolivianos1ActionPerformed
        new retboli();
        this.dispose();
    }//GEN-LAST:event_bolivianos1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(retiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(retiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(retiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(retiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new retiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel banner2;
    private javax.swing.JButton bolivianos;
    private javax.swing.JButton bolivianos1;
    private javax.swing.JLabel fechaaa;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
}
